### ISSUE TITLE
想把该项目打包集成到istoreOS中

### ISSUE THREAD

**Issue by chazikai24** [asvow/luci-app-tailscale#1]
你好，istore项目组对该项目非常感兴趣，想要打包上架istore商店，不知是否有兴趣？

**Comment by asvow** [comment]
没问题，项目本身就是参考istore商店里的tailscale插件编写的。

**Comment by chazikai24** [comment]
> 没问题，项目本身就是参考luci-app-zerotier以及istore商店里的luci-app-tailscaler插件编写的。

OK

**Comment by ssyangchn** [comment]
> > 没问题，项目本身就是参考luci-app-zerotier以及istore商店里的luci-app-tailscaler插件编写的。
> 
> OK

请问上架istore了吗
