### ISSUE TITLE
Route traffic through exit node

### ISSUE THREAD

**Issue by hkfuertes** [asvow/luci-app-tailscale#12]
Quick question, probably this is config on my part... but I was not able to make the roter be a "client" and route all my traffic through another exit node. How can I achieve this?

**Comment by asvow** [comment]
Try adding the following Additional Flags in Extra Settings: `--exit-node=<exit-node-ip>` and `--exit-node-allow-lan-access=true` .

Reference: 
- https://tailscale.com/kb/1241/tailscale-up 
- https://www.reddit.com/r/Tailscale/comments/11cih87/openwrt_tailscale_using_exit_node/

**Comment by hkfuertes** [comment]
I managed to do it... that alone was not enougth, I had to define the firewall zone and follow the steps here:
https://openwrt.org/docs/guide-user/services/vpn/tailscale/start
```
 1. Disable packet forwarding by default: Network → Firewall → General Settings

    Forward: reject

2. Disable LAN-to-WAN forwarding: Network → Firewall → Zones → lan → Edit

    Allow forward to destination zones: Ensure that your WAN zone is unselected.

```
