### ISSUE TITLE
如下新手尝试编译这个项目遇见如下问题，大佬帮忙看下可能是什么问题导致的

### ISSUE THREAD

**Issue by lizhengaas** [asvow/luci-app-tailscale#14]
系统环境为ubuntu 20.04
执行过程如下图
![image](https://github.com/user-attachments/assets/58ee984d-38b2-4b62-9bf1-35047fc1ecbc)
运行到make package/luci-app-tailscale/compile V=s这个步骤时遇见错误
[+ 18 个版本](https://github.com/openwrt/openwrt/releases)
![image](https://github.com/user-attachments/assets/f21139b8-38d8-434b-8c3d-9ab8673ab734)

**Comment by lizhengaas** [comment]
尝试重新构建还是会遇见这个问题

**Comment by asvow** [comment]
直接单独编译插件需要从openwrt官网下载对应的带预编译好toolchain的sdk进行编译。直接使用github源码不含toolchain需要先完整编译一遍固件之后才能单独编译某个插件。即：
``` shell
make download -j8
make V=s -j1
make package/luci-app-tailscale/compile V=s
```

**Comment by lizhengaas** [comment]
好的麻烦您嘞
