### ISSUE TITLE
请问一下在开了passwall2 路由器本机代理后无法打洞成功

### ISSUE THREAD

**Issue by hexsen929** [asvow/luci-app-tailscale#19]
RT，我必须重启或者关闭passwall2，等打洞成功后再开启passwall2才行。好像是走了代理？不知道有没有办法能解决，我是需要将路由器作为落地节点翻墙使用。。我尝试过将tailscale等关键字加入到passwall2直连规则中，还有41641端口，但是都不起作用。

求帮助。。。

**Comment by asvow** [comment]
对passwall2规则不了解。
直连需要放行41641端口以及tailscale相关域名，包含但不限于log.tailscale.io、tailscale.com、tailscale.net、ts.net
或者改用openclash方案：tun模式下加入下面两条规则。

```
- PROCESS-NAME,tailscale,DIRECT
- PROCESS-NAME,tailscaled,DIRECT
```

**Comment by hexsen929** [comment]
感谢，我再自己尝试下。
