### ISSUE TITLE
初学者求助，我想自定义一下，luci 内容但遇到了困难。

### ISSUE THREAD

**Issue by lizhengaas** [asvow/luci-app-tailscale#21]
我想获取wan 或lan口ip通过子网掩码识别子网地址，从而一键配置--advertise-routes 。
lan口通过uci 可以直接获取，获取wan口ip时路由器使用了dhcp，我没法识别wan口ip。麻烦您给我提供下获取wan口ip的方法。

function getLanWanSubnets() {
    return Promise.all([uci.load('network'), uci.load('dhcp')]).then(function() {
        
        let lanSubnet = null;
        let wanSubnet = null;
        // 获取 LAN 子网
        const lan = uci.sections('network', 'interface').find(section => section['.name'] === 'lan');
        if (lan && lan.ipaddr && lan.netmask) {
            lanSubnet = lan.ipaddr + '/' + calcNetmaskBits(lan.netmask);
        } else {
            console.log('LAN 配置未找到或缺少 ipaddr/netmask');
        }

        // 获取 WAN 子网      
}

**Comment by asvow** [comment]
换个思路，尝试通过`ubus call network.interface.wan status` 及 `ubus call network.interface.lan status` 获取ip

**Comment by lizhengaas** [comment]
好的十分感谢
