### ISSUE TITLE
我在测试exitnode时遇到了一个的问题

### ISSUE THREAD

**Issue by lizhengaas** [asvow/luci-app-tailscale#22]
路由器的tailscale 使用“exitnode”，
路由表中只有这个ip的路由策略“100.0.0.0/8”，
必须要重新登陆“tailscale down“ “tailscale up”之后才会添加exitnode的路由规则0.0.0.0/0

**Comment by lizhengaas** [comment]
好像创建tailscale接口的创建，会影响tailscale 路由规则的生成。
我单删掉网络接口部分时规则生成 都是正常的

**Comment by asvow** [comment]
问题无法复现，在我本机测试环境中路由表是即时生效的
<img width="1211" alt="route" src="https://github.com/user-attachments/assets/c0c70294-35f6-4fb9-9748-0eab45f0f5ed">

**Comment by lizhengaas** [comment]
您用的tailscale 版本是什么，我测试下对应版本

**Comment by asvow** [comment]
已经使用`tailscale update`官方命令 更新到最新版

> $ tailscale version
> 1.76.0
>   tailscale commit: 6d996464ad4ce520b165c0fd3a1213876e55df5a
>   other commit: d75b8cb4b03020da974de7154d6e668a36349078
>   go version: go1.23.1

**Comment by lizhengaas** [comment]
我openwrt的版本是23.05.2，tailscale版本是1.76
启动tailscale后，运行tailscale status会有以下健康检查提示
&nbsp; &nbsp; &nbsp; - adding [-m mark --mark 0x40000/0xff0000 -j MASQUERADE] in nat/ts-postrouting: running [/usr/sbin/iptables -t nat -A ts-postrouting -m mark --mark 0x40000/0xff0000 -j MASQUERADE --wait]: exit status 2: iptables v1.8.8 (nf_tables): Chain 'MASQUERADE' does not exist
Try `iptables -h' or 'iptables --help' for more information.










 ----------回复的邮件信息----------
 ***@***.***&gt; 于2024年10月16日(周三) 晚上6:39写道:

  

 
问题无法复现，在我本机测试环境中路由表是即时生效的
 route.png (view on web)

**Comment by asvow** [comment]
OpenWrt 22.03 以后已经默认使用firewall4了，基础设置`防火墙模式`请保持默认nftables。由iptables引发的问题将不做修复，请自行适配。
另外你昨天提的自动识别lan、wan口子网地址新版本已加入，可以测试一下。：）

**Comment by lizhengaas** [comment]
好的，十分感谢，
麻烦问下您这边推荐用那个版本openwrt








 ----------回复的邮件信息----------
 ***@***.***&gt; 于2024年10月16日(周三) 晚上7:07写道:

  

 
OpenWrt 22.03 以后已经默认使用firewall4了，基础设置防火墙模式请保持默认nftables。由iptables引发的问题将不做修复，请自行适配。
 另外你昨天提的自动识别lan、wan口子网地址新版本以加入，可以测试一下。：）

**Comment by asvow** [comment]
当前自用OpenWrt 23.05.5，没什么问题不建议经常更新系统，有问题推荐最新稳定版。

**Comment by lizhengaas** [comment]
麻烦问您一下，您在频繁变更配置时，路由表的规则可以同步么？








 ----------回复的邮件信息----------
 ***@***.***&gt; 于2024年10月16日(周三) 晚上7:47写道:

  

 
当前自用OpenWrt 23.05.5，没什么问题不建议经常更新系统，有问题推荐最新稳定版。

**Comment by asvow** [comment]
正常情况下，在luci页面出现`配置己应用。`提示后同步生效。调试本插件时，在测试机上需要频繁变更配置，也未遇到路由需要cli命令重启tailscale才能生效的问题。

**Comment by lizhengaas** [comment]
好的，那我再看看我得配置，您有在额外装插件适配tailscale么








 ----------回复的邮件信息----------
 ***@***.***&gt; 于2024年10月17日(周四) 晚上9:50写道:

  

 
正常情况下，在luci页面出现配置己应用。提示后同步生效。调试本插件时，在测试机上需要频繁变更配置，也未遇到路由需要cli命令重启tailscale才能生效的问题。

**Comment by asvow** [comment]
没有的。如果方便的话请分别执行
`opkg list-installed` 、`uci show network`以及`uci show tailscale`、`/etc/init.d/tailscale restart`命令，并提供相关命令输出内容以便于排查问题。（注意删除公网ip、dns等，以保护隐私）

**Comment by lizhengaas** [comment]
好的麻烦您了，周日我测试下








 ----------回复的邮件信息----------
 ***@***.***&gt; 于2024年10月17日(周四) 晚上10:47写道:

  

 
没有的。如果方便的话请分别执行
 opkg list-installed 、uci show network以及uci show tailscale命令，并提供相关命令输出内容以便于排查问题。（公网ip、dns等，注意删除以保护隐私）

**Comment by lizhengaas** [comment]
我可能知道我这边是什么问题了，但我没有找到一个比较好的解决办法，
应该是配置taislcale 属性后“保存并应用”配置，脚本执行创建网络重启网络，重启时导致路由表清空，保留了100.0.0.0/8的路由规则。
tailscale 上线时用ifup tailscale命令，模拟网络重启，重启后我这边的路由表就失效了

**Comment by lizhengaas** [comment]
我这边解决了，在获取接口并配置完成后，服务脚本里重新登录下就正常了
但我不确定这个问题是特定版本导致的还是只要个别会有此问题




 ----------回复的邮件信息----------
 ***@***.***&gt; 于2024年10月17日(周四) 晚上10:47写道:

  

 
没有的。如果方便的话请分别执行
 opkg list-installed 、uci show network以及uci show tailscale命令，并提供相关命令输出内容以便于排查问题。（公网ip、dns等，注意删除以保护隐私）
