### ISSUE TITLE
v1.2.2 自己的中继服务器无法连接

### ISSUE THREAD

**Issue by SunHHB** [asvow/luci-app-tailscale#24]
x64 ImmortalWrt 23.05.3 
openclash 
v0.46.031-beta
Redir-Host 模式
自建DERP 服务器（docker 网络正常）
tailscale netcheck 显示Nearest DERP 为自建中继服务器，  v1.2.1日志显示正常no ip v6 address（没开ipv6解析 端口转发），v1.2.2 Nearest DERP非自建中继服务器，自建服务器 没延时显示，日志显示无法连接到中继服务器DNS 显示no ip v4  address, no ip v6 address。
![QQ截图20241018194521](https://github.com/user-attachments/assets/31f804c8-7653-4573-b011-5b5445e30507)
![配置](https://github.com/user-attachments/assets/e8b96f75-0f0c-4646-bf98-2d22d9fce64b)

**Comment by SunHHB** [comment]
![日志](https://github.com/user-attachments/assets/d5210b52-1751-4b0f-aa02-d47ae2314b0f)

**Comment by asvow** [comment]
v1.2.1到v1.2.2，仅增加lan口和wan子网段luci显示，没有改动DERP 相关代码。另外你的luci看上去不是v1.2.2版本的。请清除浏览器缓存，以刷新界面。

**Comment by SunHHB** [comment]
谢谢，全新安装后，ok了。
