### ISSUE TITLE
子网设备访问异常

### ISSUE THREAD

**Issue by sgx800** [asvow/luci-app-tailscale#25]
![2024-10-28_231439](https://github.com/user-attachments/assets/ab7aff6d-c68c-41f4-b16b-638e9e2ad8dc)
![2024-10-28_231607](https://github.com/user-attachments/assets/41a341cd-e76c-46f0-b833-468d1ddb9472)

配置如图，在外地安装tailscale客户端的电脑上【远程】操作：
1. 可以访问openwrt管理页192.168.88.1，但是无法访问QNAP主页192.168.88.200；
2. 可以访问或ping通QNAP里面的虚拟机，以及bridge模式的docker，所有host模式的docker无法访问；
3. 子网另有一台电脑，ping不通，但是可以进行mstsc远程桌面连接。

**Comment by asvow** [comment]
远程桌面能访问就不是插件问题。请自行检查QNAP防火墙设置，ping不通的设备是否禁ping（windows防火墙默认禁ping）。docker网络环境复杂不做讨论。

**Comment by sgx800** [comment]
发现不编译luci，只编译tailscale和tailscaled用命令行启动时，以上访问一切正常，感觉还是luci配置有问题。
我使用的命令是tailscale up --accept-routes --advertise-routes=192.168.88.0/24 --advertise-exit-node --stateful-filtering=false
防火墙模式iptable，OP版本Lean LEDE R24.10.24 / LuCI openwrt-23.05 branch git-24.296.38024-3024d02

**Comment by asvow** [comment]
`--stateful-filtering=false` 这个配置添加到luci的`附加设置`里。如果还有问题请参考openwrt官方主线，修改防火墙为fw4，同时模式设置为nftable。iptable模式引发的问题这里不考虑修复。
