### ISSUE TITLE
安装后的配置文件和子网互通问题

### ISSUE THREAD

**Issue by knlvz** [asvow/luci-app-tailscale#26]
### 问题描述

1. 按照安装命令进行安装，安装后的配置文件和tailscale有冲突，需要ssh到路由器在目录`/etc/config/`里面把luci-app-tailscale替换掉tailscale的配置文件，才能正常使用luci-app-tailscale
```
opkg update
opkg install --force-overwrite /tmp/luci-*-tailscale*.ipk
```
2.启用子网互通后，自动配置的静态路由无法连通对方子网，需要修改才能连通，软路由使用的防火墙为nftables
```
接口：tailscale生成的接口
目标：对方子网段
网关：tailscale分配的IP
```
### 软路由使用的固件
ImmortalWrt 23.05.4
### 安装的tailscale版本
tailscale 1.58.2-1
luci-app-tailscale 1.2.2
luci-i18n-tailscale-zh-cn 241016.39604
自建的Headscale 0.23.0
自建的derp
### 网络环境
本地子网：192.168.10.0/24
对方子网：192.168.2.0/24
tailscale分配给本路由器IP为：10.254.254.2
### 附件图
![1无法连通子网3](https://github.com/user-attachments/assets/fde2a771-d050-4e66-b8ef-6441300eeea8)
![2无法连通子网1](https://github.com/user-attachments/assets/be77802f-fb9d-42e1-8d15-70097f1340a3)
![3无法连通子网2](https://github.com/user-attachments/assets/e8c825dd-5b9e-4217-aa1a-4734ef0ee9d1)
![4无法连通子网](https://github.com/user-attachments/assets/cfc1ca56-757f-45c5-9851-a63fa8ba6acd)
![6无法连通子网5](https://github.com/user-attachments/assets/600a0d69-7e07-486d-ada7-c96bb535a087)

**Comment by SunHHB** [comment]
我的上个版本是可以的，就是需要重启下路由器。
