### ISSUE TITLE
Needs re-login everytime restarted the service

### ISSUE THREAD

**Issue by fanchangyong** [asvow/luci-app-tailscale#27]
It seems it'll require to re-login on Tailscale when restarted the service, is it expected behavior?

**Comment by asvow** [comment]
Under the default configuration, user information is stored in the /etc/tailscale directory. Unless the Tailscale key expires, there is no need to re-login.

**Comment by fanchangyong** [comment]
I used the official guide to manually setup tailscale before: https://openwrt.org/docs/guide-user/services/vpn/tailscale/start .
Is it possible that some legacy configuration files caused the issue?

Another issue I encountered is: I specified `Exit Node` and `Expose Subnets` on the UI, but it did not take effect.

**Comment by fanchangyong** [comment]
Edit: The issue is I did not check the `Accept Routes` option, it works perfectly fine after I turn on the option.

Thank you! This is a wonderful project!


I removed the files in `/etc/tailscale` and reinstalled tailsclae and luci-app-tailscale, the above issues was solved.

But I still can not access the internet via Exit Node. 
Do you have any ideas about possible reasons?
