### ISSUE TITLE
请问如何升级tailscale版本呢

### ISSUE THREAD

**Issue by hexsen929** [asvow/luci-app-tailscale#3]
你好，我使用openwrt-K编译无法成功，现在使用大佬编译好的文件安装的，我从官网下载tailscale_1.62.0_amd64.tgz 09-52-58-678.tgz替换/usr/sbin下面的文件能启动，无法显示登陆信息，可以启动。。

**Comment by bxb100** [comment]
前端 bug, 等我 PR 修复一波
