### ISSUE TITLE
提个建议

### ISSUE THREAD

**Issue by chazikai24** [asvow/luci-app-tailscale#4]
因 tailscale 占用了 config/tailscale 和 init.d/tailscale ，可以参照Carseason/openwrt-tailscale的方案更合适。

**Comment by asvow** [comment]
强迫症接受不了:( ，luci-app-zerotier和zerotier也同时使用 init.d/zerotier，并不冲突。该问题根源可能在于上游tailscale文件路径及Makefile编写问题导致，期待上游参考zerotier做出调整。这段时间比较忙，得空了考虑提PR🙂
