### ISSUE TITLE
ucode依赖是必须的吗？

### ISSUE THREAD

**Issue by 0x5826** [asvow/luci-app-tailscale#6]
OpenWrt21.02的luci js版本没有ucode这个工具，查阅了下是从op22开始引入的

**Comment by asvow** [comment]
感谢提醒，当初参考[luci-app-zerotier](https://github.com/immortalwrt/luci/blob/master/applications/luci-app-zerotier/Makefile)项目引入 jsonfilter 和ucode两个依赖。实际在本项目中未使用，将在下一个版本中移除。
