### ISSUE TITLE
强制安装成功后 左侧菜单没有tailscale

### ISSUE THREAD

**Issue by lll-gr** [asvow/luci-app-tailscale#7]
root@L:/tmp# opkg install --force-overwrite luci-i18n-tailscale-zh-cn_240611.42655_all.ipk 
Package luci-i18n-tailscale-zh-cn (240611.42655) installed in root is up to date.

**Comment by lll-gr** [comment]
/tmp# opkg install --force-overwrite luci-app-tailscale_1.1.1_all.ipk 
Installing luci-app-tailscale (1.1.1) to root...
Configuring luci-app-tailscale.
uci: Parse error (invalid command) at line 1, byte 0
disabled in config
disabled in config

**Comment by asvow** [comment]
本插件仅适用于openwrt/immortalwrt官方luci2分支版本固件。大雕LEDE源码中默认为luci1版本无法使用，需要在编译固件前修改`feeds.conf.default`切换luci至`openwrt-23.05`分支。

另外`uci: Parse error (invalid command) `报错可通过以下命令排查
```
for CONF in /etc/config/* ; do uci show "${CONF##*/}" > /dev/null || echo "${CONF}"; done
```
