### ISSUE TITLE
Site to site VPN

### ISSUE THREAD

**Issue by dhanuhammer** [asvow/luci-app-tailscale#8]
The app has an option for 'Site to site' networking in theglobal settings tab.
What is it used for? Is it a replacement for '--snat-subnet-routes=false' tag?

**Comment by asvow** [comment]
It adds the flags `--snat-subnet-routes=false` and `--stateful-filtering=false`, as referenced in the link https://tailscale.com/kb/1214/site-to-site

**Comment by dhanuhammer** [comment]
it seems like the checkbox does not work, because i mentioned the snat flag
explicitly in extra settings tab and the subnet site to site worked
